/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 30
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 32
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LT_PERCENT_AT = 1,
  anon_sym_EQ = 2,
  aux_sym_asp_directive_token1 = 3,
  anon_sym_PERCENT_GT = 4,
  anon_sym_LT_PERCENT_EQ = 5,
  anon_sym_LT_PERCENT = 6,
  aux_sym_server_script_block_token1 = 7,
  aux_sym_server_script_block_token2 = 8,
  anon_sym_LT_BANG_DASH_DASH = 9,
  anon_sym_POUNDinclude = 10,
  aux_sym_include_directive_token1 = 11,
  aux_sym_include_directive_token2 = 12,
  anon_sym_DASH_DASH_GT = 13,
  sym_comment = 14,
  sym_string = 15,
  sym_number = 16,
  sym_identifier = 17,
  sym_operator = 18,
  sym_punctuation = 19,
  sym_html_content = 20,
  sym_html_lt = 21,
  sym_source_file = 22,
  sym_asp_directive = 23,
  sym_asp_expression = 24,
  sym_asp_block = 25,
  sym_server_script_block = 26,
  sym_include_directive = 27,
  sym__code_token = 28,
  aux_sym_source_file_repeat1 = 29,
  aux_sym_asp_directive_repeat1 = 30,
  aux_sym_asp_expression_repeat1 = 31,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT_PERCENT_AT] = "<%@",
  [anon_sym_EQ] = "=",
  [aux_sym_asp_directive_token1] = "asp_directive_token1",
  [anon_sym_PERCENT_GT] = "%>",
  [anon_sym_LT_PERCENT_EQ] = "<%=",
  [anon_sym_LT_PERCENT] = "<%",
  [aux_sym_server_script_block_token1] = "server_script_block_token1",
  [aux_sym_server_script_block_token2] = "server_script_block_token2",
  [anon_sym_LT_BANG_DASH_DASH] = "<!--",
  [anon_sym_POUNDinclude] = "#include",
  [aux_sym_include_directive_token1] = "include_directive_token1",
  [aux_sym_include_directive_token2] = "include_directive_token2",
  [anon_sym_DASH_DASH_GT] = "-->",
  [sym_comment] = "comment",
  [sym_string] = "string",
  [sym_number] = "number",
  [sym_identifier] = "identifier",
  [sym_operator] = "operator",
  [sym_punctuation] = "punctuation",
  [sym_html_content] = "html_content",
  [sym_html_lt] = "html_lt",
  [sym_source_file] = "source_file",
  [sym_asp_directive] = "asp_directive",
  [sym_asp_expression] = "asp_expression",
  [sym_asp_block] = "asp_block",
  [sym_server_script_block] = "server_script_block",
  [sym_include_directive] = "include_directive",
  [sym__code_token] = "_code_token",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_asp_directive_repeat1] = "asp_directive_repeat1",
  [aux_sym_asp_expression_repeat1] = "asp_expression_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT_PERCENT_AT] = anon_sym_LT_PERCENT_AT,
  [anon_sym_EQ] = anon_sym_EQ,
  [aux_sym_asp_directive_token1] = aux_sym_asp_directive_token1,
  [anon_sym_PERCENT_GT] = anon_sym_PERCENT_GT,
  [anon_sym_LT_PERCENT_EQ] = anon_sym_LT_PERCENT_EQ,
  [anon_sym_LT_PERCENT] = anon_sym_LT_PERCENT,
  [aux_sym_server_script_block_token1] = aux_sym_server_script_block_token1,
  [aux_sym_server_script_block_token2] = aux_sym_server_script_block_token2,
  [anon_sym_LT_BANG_DASH_DASH] = anon_sym_LT_BANG_DASH_DASH,
  [anon_sym_POUNDinclude] = anon_sym_POUNDinclude,
  [aux_sym_include_directive_token1] = aux_sym_include_directive_token1,
  [aux_sym_include_directive_token2] = aux_sym_include_directive_token2,
  [anon_sym_DASH_DASH_GT] = anon_sym_DASH_DASH_GT,
  [sym_comment] = sym_comment,
  [sym_string] = sym_string,
  [sym_number] = sym_number,
  [sym_identifier] = sym_identifier,
  [sym_operator] = sym_operator,
  [sym_punctuation] = sym_punctuation,
  [sym_html_content] = sym_html_content,
  [sym_html_lt] = sym_html_lt,
  [sym_source_file] = sym_source_file,
  [sym_asp_directive] = sym_asp_directive,
  [sym_asp_expression] = sym_asp_expression,
  [sym_asp_block] = sym_asp_block,
  [sym_server_script_block] = sym_server_script_block,
  [sym_include_directive] = sym_include_directive,
  [sym__code_token] = sym__code_token,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_asp_directive_repeat1] = aux_sym_asp_directive_repeat1,
  [aux_sym_asp_expression_repeat1] = aux_sym_asp_expression_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT_PERCENT_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_asp_directive_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PERCENT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_PERCENT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_server_script_block_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_server_script_block_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LT_BANG_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDinclude] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_include_directive_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_include_directive_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DASH_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_punctuation] = {
    .visible = true,
    .named = true,
  },
  [sym_html_content] = {
    .visible = true,
    .named = true,
  },
  [sym_html_lt] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_asp_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_asp_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_asp_block] = {
    .visible = true,
    .named = true,
  },
  [sym_server_script_block] = {
    .visible = true,
    .named = true,
  },
  [sym_include_directive] = {
    .visible = true,
    .named = true,
  },
  [sym__code_token] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_asp_directive_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_asp_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 18,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(73);
      ADVANCE_MAP(
        '"', 3,
        '#', 30,
        '%', 11,
        '&', 107,
        '\'', 93,
        '<', 104,
        '=', 75,
        '>', 106,
        'F', 44,
        'f', 44,
        'R', 40,
        'r', 40,
        'V', 45,
        'v', 45,
        '(', 109,
        ')', 109,
        ',', 109,
        '.', 109,
        ':', 109,
        '*', 103,
        '+', 103,
        '-', 103,
        '/', 103,
        '\\', 103,
        '^', 103,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(95);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '"', 3,
        '%', 11,
        '&', 107,
        '\'', 93,
        '<', 108,
        '>', 106,
        'R', 100,
        'r', 100,
        '(', 109,
        ')', 109,
        ',', 109,
        '.', 109,
        ':', 109,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('*' <= lookahead && lookahead <= '/') ||
          lookahead == '=' ||
          lookahead == '\\' ||
          lookahead == '^') ADVANCE(103);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(95);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '"', 3,
        '&', 107,
        '\'', 93,
        '<', 105,
        '>', 106,
        'R', 100,
        'r', 100,
        '(', 109,
        ')', 109,
        ',', 109,
        '.', 109,
        ':', 109,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('*' <= lookahead && lookahead <= '/') ||
          lookahead == '=' ||
          lookahead == '\\' ||
          lookahead == '^') ADVANCE(103);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(95);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(94);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(77);
      if (lookahead == '%') ADVANCE(11);
      if (lookahead == '\'') ADVANCE(81);
      if (lookahead == '=') ADVANCE(75);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(79);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(78);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      if (lookahead != 0) ADVANCE(76);
      END_STATE();
    case 5:
      if (lookahead == '\'') ADVANCE(93);
      if (lookahead == '-') ADVANCE(8);
      if (lookahead == '=') ADVANCE(75);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(40);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(87);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(6);
      END_STATE();
    case 8:
      if (lookahead == '-') ADVANCE(26);
      END_STATE();
    case 9:
      if (lookahead == '=') ADVANCE(35);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(58);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '=' &&
          lookahead != '>') ADVANCE(59);
      END_STATE();
    case 10:
      if (lookahead == '=') ADVANCE(13);
      if (lookahead == '>') ADVANCE(85);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(10);
      if (lookahead != 0) ADVANCE(23);
      END_STATE();
    case 11:
      if (lookahead == '>') ADVANCE(82);
      END_STATE();
    case 12:
      if (lookahead == '>') ADVANCE(85);
      if (lookahead == '"' ||
          lookahead == '\'') ADVANCE(23);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(22);
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(17);
      if (lookahead != 0) ADVANCE(23);
      END_STATE();
    case 13:
      if (lookahead == '>') ADVANCE(85);
      if (lookahead == '"' ||
          lookahead == '\'') ADVANCE(19);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(22);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(13);
      if (lookahead != 0) ADVANCE(23);
      END_STATE();
    case 14:
      if (lookahead == '>') ADVANCE(85);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(20);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(22);
      if (lookahead != 0) ADVANCE(23);
      END_STATE();
    case 15:
      if (lookahead == '>') ADVANCE(85);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(24);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(22);
      if (lookahead != 0) ADVANCE(23);
      END_STATE();
    case 16:
      if (lookahead == '>') ADVANCE(85);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(18);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(22);
      if (lookahead != 0) ADVANCE(23);
      END_STATE();
    case 17:
      if (lookahead == '>') ADVANCE(85);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(14);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(22);
      if (lookahead != 0) ADVANCE(23);
      END_STATE();
    case 18:
      if (lookahead == '>') ADVANCE(85);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(12);
      if (lookahead != 0) ADVANCE(23);
      END_STATE();
    case 19:
      if (lookahead == '>') ADVANCE(85);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(22);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(15);
      if (lookahead != 0) ADVANCE(23);
      END_STATE();
    case 20:
      if (lookahead == '>') ADVANCE(85);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(22);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(10);
      if (lookahead != 0) ADVANCE(23);
      END_STATE();
    case 21:
      if (lookahead == '>') ADVANCE(85);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(22);
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(17);
      if (lookahead == 'V' ||
          lookahead == 'v') ADVANCE(16);
      if (lookahead != 0) ADVANCE(23);
      END_STATE();
    case 22:
      if (lookahead == '>') ADVANCE(85);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(22);
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(17);
      if (lookahead != 0) ADVANCE(23);
      END_STATE();
    case 23:
      if (lookahead == '>') ADVANCE(85);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(22);
      if (lookahead != 0) ADVANCE(23);
      END_STATE();
    case 24:
      if (lookahead == '>') ADVANCE(85);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(21);
      if (lookahead != 0) ADVANCE(23);
      END_STATE();
    case 25:
      if (lookahead == '>') ADVANCE(86);
      END_STATE();
    case 26:
      if (lookahead == '>') ADVANCE(91);
      END_STATE();
    case 27:
      if (lookahead == 'c') ADVANCE(31);
      END_STATE();
    case 28:
      if (lookahead == 'd') ADVANCE(29);
      END_STATE();
    case 29:
      if (lookahead == 'e') ADVANCE(88);
      END_STATE();
    case 30:
      if (lookahead == 'i') ADVANCE(32);
      END_STATE();
    case 31:
      if (lookahead == 'l') ADVANCE(33);
      END_STATE();
    case 32:
      if (lookahead == 'n') ADVANCE(27);
      END_STATE();
    case 33:
      if (lookahead == 'u') ADVANCE(28);
      END_STATE();
    case 34:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(93);
      END_STATE();
    case 35:
      if (lookahead == '"' ||
          lookahead == '\'') ADVANCE(55);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(58);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(42);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(59);
      END_STATE();
    case 36:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(56);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(59);
      END_STATE();
    case 37:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(48);
      END_STATE();
    case 38:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(62);
      END_STATE();
    case 39:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(63);
      END_STATE();
    case 40:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(50);
      END_STATE();
    case 41:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(89);
      END_STATE();
    case 42:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(60);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(59);
      END_STATE();
    case 43:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(61);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(59);
      END_STATE();
    case 44:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(49);
      END_STATE();
    case 45:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(54);
      END_STATE();
    case 46:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(52);
      END_STATE();
    case 47:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(53);
      END_STATE();
    case 48:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(90);
      END_STATE();
    case 49:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(41);
      END_STATE();
    case 50:
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(34);
      END_STATE();
    case 51:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(36);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(59);
      END_STATE();
    case 52:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(66);
      END_STATE();
    case 53:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(67);
      END_STATE();
    case 54:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(65);
      END_STATE();
    case 55:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(58);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(59);
      END_STATE();
    case 56:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(58);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(59);
      END_STATE();
    case 57:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(58);
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(51);
      if (lookahead == 'V' ||
          lookahead == 'v') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(59);
      END_STATE();
    case 58:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(58);
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(59);
      END_STATE();
    case 59:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(59);
      END_STATE();
    case 60:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(59);
      END_STATE();
    case 61:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(59);
      END_STATE();
    case 62:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(46);
      END_STATE();
    case 63:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(47);
      END_STATE();
    case 64:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(39);
      END_STATE();
    case 65:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(68);
      END_STATE();
    case 66:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(59);
      END_STATE();
    case 67:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(25);
      END_STATE();
    case 68:
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(37);
      END_STATE();
    case 69:
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(96);
      END_STATE();
    case 70:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(97);
      END_STATE();
    case 71:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(98);
      END_STATE();
    case 72:
      if (eof) ADVANCE(73);
      if (lookahead == '\'') ADVANCE(92);
      if (lookahead == '<') ADVANCE(115);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(112);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(110);
      if (lookahead != 0) ADVANCE(114);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT_AT);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym_asp_directive_token1);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym_asp_directive_token1);
      if (lookahead == '"') ADVANCE(94);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym_asp_directive_token1);
      if (lookahead == '"') ADVANCE(77);
      if (lookahead == '\'') ADVANCE(81);
      if (lookahead == '=') ADVANCE(75);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(79);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(78);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      if (lookahead != 0 &&
          lookahead != '%') ADVANCE(76);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(aux_sym_asp_directive_token1);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(101);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(aux_sym_asp_directive_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(aux_sym_asp_directive_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(93);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_PERCENT_GT);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT_EQ);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT);
      if (lookahead == '=') ADVANCE(83);
      if (lookahead == '@') ADVANCE(74);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(aux_sym_server_script_block_token1);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(aux_sym_server_script_block_token2);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_LT_BANG_DASH_DASH);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_POUNDinclude);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(aux_sym_include_directive_token1);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(aux_sym_include_directive_token2);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_DASH_DASH_GT);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '<') ADVANCE(93);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(92);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(93);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(95);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(96);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(97);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(98);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(93);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(101);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(99);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_operator);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '!') ADVANCE(7);
      if (lookahead == '=' ||
          lookahead == '>') ADVANCE(103);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '/') ADVANCE(64);
      if (lookahead == '=' ||
          lookahead == '>') ADVANCE(103);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '=') ADVANCE(103);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == 'H') ADVANCE(71);
      if (lookahead == 'O') ADVANCE(69);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '=' ||
          lookahead == '>') ADVANCE(103);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_punctuation);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_html_content);
      if (lookahead == '\'') ADVANCE(92);
      if (lookahead == '<') ADVANCE(115);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(112);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(110);
      if (lookahead != 0) ADVANCE(114);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_html_content);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(92);
      if (lookahead != 0 &&
          lookahead != '<') ADVANCE(114);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_html_content);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(113);
      if (lookahead != 0 &&
          lookahead != '<') ADVANCE(114);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_html_content);
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(111);
      if (lookahead != 0 &&
          lookahead != '<') ADVANCE(114);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_html_content);
      if (lookahead != 0 &&
          lookahead != '<') ADVANCE(114);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_html_lt);
      if (lookahead == '!') ADVANCE(7);
      if (lookahead == '%') ADVANCE(84);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(38);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 72},
  [2] = {.lex_state = 72},
  [3] = {.lex_state = 72},
  [4] = {.lex_state = 72},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 72},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 72},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 72},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 72},
  [15] = {.lex_state = 72},
  [16] = {.lex_state = 72},
  [17] = {.lex_state = 72},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 72},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 4},
  [22] = {.lex_state = 4},
  [23] = {.lex_state = 4},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 5},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 5},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_PERCENT_GT] = ACTIONS(1),
    [anon_sym_LT_BANG_DASH_DASH] = ACTIONS(1),
    [anon_sym_POUNDinclude] = ACTIONS(1),
    [aux_sym_include_directive_token1] = ACTIONS(1),
    [aux_sym_include_directive_token2] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_operator] = ACTIONS(1),
    [sym_punctuation] = ACTIONS(1),
    [sym_html_lt] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(25),
    [sym_asp_directive] = STATE(2),
    [sym_asp_expression] = STATE(2),
    [sym_asp_block] = STATE(2),
    [sym_server_script_block] = STATE(2),
    [sym_include_directive] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LT_PERCENT_AT] = ACTIONS(7),
    [anon_sym_LT_PERCENT_EQ] = ACTIONS(9),
    [anon_sym_LT_PERCENT] = ACTIONS(11),
    [aux_sym_server_script_block_token1] = ACTIONS(13),
    [anon_sym_LT_BANG_DASH_DASH] = ACTIONS(15),
    [sym_comment] = ACTIONS(17),
    [sym_html_content] = ACTIONS(19),
    [sym_html_lt] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(7), 1,
      anon_sym_LT_PERCENT_AT,
    ACTIONS(9), 1,
      anon_sym_LT_PERCENT_EQ,
    ACTIONS(11), 1,
      anon_sym_LT_PERCENT,
    ACTIONS(13), 1,
      aux_sym_server_script_block_token1,
    ACTIONS(15), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(17), 1,
      sym_comment,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 2,
      sym_html_content,
      sym_html_lt,
    STATE(3), 6,
      sym_asp_directive,
      sym_asp_expression,
      sym_asp_block,
      sym_server_script_block,
      sym_include_directive,
      aux_sym_source_file_repeat1,
  [34] = 9,
    ACTIONS(17), 1,
      sym_comment,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    ACTIONS(27), 1,
      anon_sym_LT_PERCENT_AT,
    ACTIONS(30), 1,
      anon_sym_LT_PERCENT_EQ,
    ACTIONS(33), 1,
      anon_sym_LT_PERCENT,
    ACTIONS(36), 1,
      aux_sym_server_script_block_token1,
    ACTIONS(39), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(42), 2,
      sym_html_content,
      sym_html_lt,
    STATE(3), 6,
      sym_asp_directive,
      sym_asp_expression,
      sym_asp_block,
      sym_server_script_block,
      sym_include_directive,
      aux_sym_source_file_repeat1,
  [68] = 3,
    ACTIONS(17), 1,
      sym_comment,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
    ACTIONS(47), 7,
      anon_sym_LT_PERCENT_AT,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT,
      aux_sym_server_script_block_token1,
      anon_sym_LT_BANG_DASH_DASH,
      sym_html_content,
      sym_html_lt,
  [84] = 4,
    ACTIONS(49), 1,
      anon_sym_PERCENT_GT,
    ACTIONS(53), 2,
      sym_identifier,
      sym_operator,
    STATE(11), 2,
      sym__code_token,
      aux_sym_asp_expression_repeat1,
    ACTIONS(51), 4,
      sym_comment,
      sym_string,
      sym_number,
      sym_punctuation,
  [102] = 4,
    ACTIONS(55), 1,
      aux_sym_server_script_block_token2,
    ACTIONS(59), 2,
      sym_identifier,
      sym_operator,
    STATE(13), 2,
      sym__code_token,
      aux_sym_asp_expression_repeat1,
    ACTIONS(57), 4,
      sym_comment,
      sym_string,
      sym_number,
      sym_punctuation,
  [120] = 4,
    ACTIONS(61), 1,
      anon_sym_PERCENT_GT,
    ACTIONS(65), 2,
      sym_identifier,
      sym_operator,
    STATE(9), 2,
      sym__code_token,
      aux_sym_asp_expression_repeat1,
    ACTIONS(63), 4,
      sym_comment,
      sym_string,
      sym_number,
      sym_punctuation,
  [138] = 3,
    ACTIONS(17), 1,
      sym_comment,
    ACTIONS(67), 1,
      ts_builtin_sym_end,
    ACTIONS(69), 7,
      anon_sym_LT_PERCENT_AT,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT,
      aux_sym_server_script_block_token1,
      anon_sym_LT_BANG_DASH_DASH,
      sym_html_content,
      sym_html_lt,
  [154] = 4,
    ACTIONS(71), 1,
      anon_sym_PERCENT_GT,
    ACTIONS(75), 2,
      sym_identifier,
      sym_operator,
    STATE(18), 2,
      sym__code_token,
      aux_sym_asp_expression_repeat1,
    ACTIONS(73), 4,
      sym_comment,
      sym_string,
      sym_number,
      sym_punctuation,
  [172] = 3,
    ACTIONS(17), 1,
      sym_comment,
    ACTIONS(77), 1,
      ts_builtin_sym_end,
    ACTIONS(79), 7,
      anon_sym_LT_PERCENT_AT,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT,
      aux_sym_server_script_block_token1,
      anon_sym_LT_BANG_DASH_DASH,
      sym_html_content,
      sym_html_lt,
  [188] = 4,
    ACTIONS(81), 1,
      anon_sym_PERCENT_GT,
    ACTIONS(75), 2,
      sym_identifier,
      sym_operator,
    STATE(18), 2,
      sym__code_token,
      aux_sym_asp_expression_repeat1,
    ACTIONS(73), 4,
      sym_comment,
      sym_string,
      sym_number,
      sym_punctuation,
  [206] = 3,
    ACTIONS(17), 1,
      sym_comment,
    ACTIONS(83), 1,
      ts_builtin_sym_end,
    ACTIONS(85), 7,
      anon_sym_LT_PERCENT_AT,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT,
      aux_sym_server_script_block_token1,
      anon_sym_LT_BANG_DASH_DASH,
      sym_html_content,
      sym_html_lt,
  [222] = 4,
    ACTIONS(87), 1,
      aux_sym_server_script_block_token2,
    ACTIONS(91), 2,
      sym_identifier,
      sym_operator,
    STATE(20), 2,
      sym__code_token,
      aux_sym_asp_expression_repeat1,
    ACTIONS(89), 4,
      sym_comment,
      sym_string,
      sym_number,
      sym_punctuation,
  [240] = 3,
    ACTIONS(17), 1,
      sym_comment,
    ACTIONS(93), 1,
      ts_builtin_sym_end,
    ACTIONS(95), 7,
      anon_sym_LT_PERCENT_AT,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT,
      aux_sym_server_script_block_token1,
      anon_sym_LT_BANG_DASH_DASH,
      sym_html_content,
      sym_html_lt,
  [256] = 3,
    ACTIONS(17), 1,
      sym_comment,
    ACTIONS(97), 1,
      ts_builtin_sym_end,
    ACTIONS(99), 7,
      anon_sym_LT_PERCENT_AT,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT,
      aux_sym_server_script_block_token1,
      anon_sym_LT_BANG_DASH_DASH,
      sym_html_content,
      sym_html_lt,
  [272] = 3,
    ACTIONS(17), 1,
      sym_comment,
    ACTIONS(101), 1,
      ts_builtin_sym_end,
    ACTIONS(103), 7,
      anon_sym_LT_PERCENT_AT,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT,
      aux_sym_server_script_block_token1,
      anon_sym_LT_BANG_DASH_DASH,
      sym_html_content,
      sym_html_lt,
  [288] = 3,
    ACTIONS(17), 1,
      sym_comment,
    ACTIONS(105), 1,
      ts_builtin_sym_end,
    ACTIONS(107), 7,
      anon_sym_LT_PERCENT_AT,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT,
      aux_sym_server_script_block_token1,
      anon_sym_LT_BANG_DASH_DASH,
      sym_html_content,
      sym_html_lt,
  [304] = 4,
    ACTIONS(109), 1,
      anon_sym_PERCENT_GT,
    ACTIONS(114), 2,
      sym_identifier,
      sym_operator,
    STATE(18), 2,
      sym__code_token,
      aux_sym_asp_expression_repeat1,
    ACTIONS(111), 4,
      sym_comment,
      sym_string,
      sym_number,
      sym_punctuation,
  [322] = 3,
    ACTIONS(17), 1,
      sym_comment,
    ACTIONS(117), 1,
      ts_builtin_sym_end,
    ACTIONS(119), 7,
      anon_sym_LT_PERCENT_AT,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT,
      aux_sym_server_script_block_token1,
      anon_sym_LT_BANG_DASH_DASH,
      sym_html_content,
      sym_html_lt,
  [338] = 4,
    ACTIONS(109), 1,
      aux_sym_server_script_block_token2,
    ACTIONS(124), 2,
      sym_identifier,
      sym_operator,
    STATE(20), 2,
      sym__code_token,
      aux_sym_asp_expression_repeat1,
    ACTIONS(121), 4,
      sym_comment,
      sym_string,
      sym_number,
      sym_punctuation,
  [356] = 4,
    ACTIONS(17), 1,
      sym_comment,
    ACTIONS(129), 1,
      anon_sym_PERCENT_GT,
    STATE(22), 1,
      aux_sym_asp_directive_repeat1,
    ACTIONS(127), 4,
      anon_sym_EQ,
      aux_sym_asp_directive_token1,
      sym_string,
      sym_identifier,
  [372] = 4,
    ACTIONS(17), 1,
      sym_comment,
    ACTIONS(133), 1,
      anon_sym_PERCENT_GT,
    STATE(23), 1,
      aux_sym_asp_directive_repeat1,
    ACTIONS(131), 4,
      anon_sym_EQ,
      aux_sym_asp_directive_token1,
      sym_string,
      sym_identifier,
  [388] = 4,
    ACTIONS(17), 1,
      sym_comment,
    ACTIONS(138), 1,
      anon_sym_PERCENT_GT,
    STATE(23), 1,
      aux_sym_asp_directive_repeat1,
    ACTIONS(135), 4,
      anon_sym_EQ,
      aux_sym_asp_directive_token1,
      sym_string,
      sym_identifier,
  [404] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 2,
      aux_sym_include_directive_token1,
      aux_sym_include_directive_token2,
  [412] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 1,
      ts_builtin_sym_end,
  [419] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 1,
      anon_sym_POUNDinclude,
  [426] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 1,
      anon_sym_EQ,
  [433] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 1,
      sym_string,
  [440] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 1,
      anon_sym_DASH_DASH_GT,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 34,
  [SMALL_STATE(4)] = 68,
  [SMALL_STATE(5)] = 84,
  [SMALL_STATE(6)] = 102,
  [SMALL_STATE(7)] = 120,
  [SMALL_STATE(8)] = 138,
  [SMALL_STATE(9)] = 154,
  [SMALL_STATE(10)] = 172,
  [SMALL_STATE(11)] = 188,
  [SMALL_STATE(12)] = 206,
  [SMALL_STATE(13)] = 222,
  [SMALL_STATE(14)] = 240,
  [SMALL_STATE(15)] = 256,
  [SMALL_STATE(16)] = 272,
  [SMALL_STATE(17)] = 288,
  [SMALL_STATE(18)] = 304,
  [SMALL_STATE(19)] = 322,
  [SMALL_STATE(20)] = 338,
  [SMALL_STATE(21)] = 356,
  [SMALL_STATE(22)] = 372,
  [SMALL_STATE(23)] = 388,
  [SMALL_STATE(24)] = 404,
  [SMALL_STATE(25)] = 412,
  [SMALL_STATE(26)] = 419,
  [SMALL_STATE(27)] = 426,
  [SMALL_STATE(28)] = 433,
  [SMALL_STATE(29)] = 440,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_asp_directive, 2, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_asp_directive, 2, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_asp_expression, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_asp_expression, 2, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_asp_block, 2, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_asp_block, 2, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_server_script_block, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_server_script_block, 2, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [91] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_server_script_block, 3, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_server_script_block, 3, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_asp_directive, 3, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_asp_directive, 3, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_asp_expression, 3, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_asp_expression, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_asp_block, 3, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_asp_block, 3, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_asp_expression_repeat1, 2, 0, 0),
  [111] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_asp_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [114] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_asp_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include_directive, 6, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_include_directive, 6, 0, 0),
  [121] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_asp_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [124] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_asp_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [127] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [131] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [135] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_asp_directive_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_asp_directive_repeat1, 2, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [142] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_asp_classic(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "asp_classic",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
